"""
Django settings for Roomkhojlo_api_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$h6b14ci412m(v&-3qx-*18&u!%uth*tdlg7w&#e&eakg+nh-v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'Roomkhojlo_APP',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

ROOT_URLCONF = 'Roomkhojlo_api_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Roomkhojlo_api_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
    
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'test_1',
#         'USER': 'Rohit',
#         'PASSWORD': 'rohit12',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(default="mysql://root:XSMTPiHfUudRkBhCEkEFhfhQlpBeeweV@mysql.railway.internal:3306/railway")
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'Roomkhojlo_APP.custom_token.MultiModelTokenAuthentication',
    ),
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
        
    # ]
}

# AUTHENTICATION_BACKENDS = [
#     'Roomkhojlo_APP.auth.MultiModelAuthBackend',
# ]

#media files  which upload 
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#################################### start cors headers ##################################################

#cors handlers
CORS_ALLOW_ALL_ORIGINS = True  # Allows all domains

#cors methods 
# CORS_ALLOW_METHODS = [
#     'GET',
#     'POST',
#     'PUT',
#     'DELETE',
#     'PATCH',
#     'OPTIONS',  # Add OPTIONS for preflight requests
# ]

#cors headers
# CORS_ALLOW_HEADERS = [
#     "x-requested-with",   # AJAX requests
#     "content-type",       # JSON/Form data
#     "accept",             # Expected response format
#     "origin",             # Identifies the request origin
#     "accept-encoding",    # Compression support
#     "authorization",      # JWT/API keys
#     "cache-control",      # Caching behavior
#     "accept-language",    # Language preference
# ]

#cors origins
# CORS_ALLOWED_ORIGINS = [
#     "http://192.168.1.9:8000",  # React frontend
# ]

# CORS_EXPOSE_HEADERS = [
#     "Content-Disposition",
# ]

# CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# CORS_REPLACE_HTTPS_REFERER = True  # or False


# CORS_ALLOW_CREDENTIALS = True  # Allow cookies and authentication headers if needed

# SESSION_COOKIE_SAMESITE = "None"  # Required for cross-site cookies
# SESSION_COOKIE_SECURE = True  # Required if using HTTPS

#################################### end cors headers ##################################################