[phases.setup]
nixPkgs = ["python311", "pkg-config", "mariadb-connector-c"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

