# Generated by Django 5.1.4 on 2025-04-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('agency_name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('alternate_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, default='agent_photos/default.jpg', null=True, upload_to='agent_photos/')),
                ('id_proof_type', models.CharField(max_length=150)),
                ('id_proof_number', models.CharField(max_length=150)),
                ('empId', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default='true', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
                'db_table': 'table_agent',
            },
        ),
        migrations.CreateModel(
            name='empolyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('salary', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, default='employee_photos/default.jpg', null=True, upload_to='employee_photos/')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], default='employee', max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('password', models.CharField(max_length=150)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default='true', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'table_employee',
            },
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('occupancy', models.CharField(default='single', max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('assigned_to', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('is_active', models.CharField(default='true', max_length=10)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'enquiry',
                'verbose_name_plural': 'enquiries',
                'db_table': 'table_enquiry',
            },
        ),
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, default='tenant_photos/default.jpg', null=True, upload_to='tenant_photos/')),
                ('password', models.CharField(max_length=150)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default='true', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'db_table': 'table_tenant',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('user_type', models.CharField(choices=[('tenant', 'tenant'), ('landlord', 'landlord')], default='tenant', max_length=10)),
                ('password', models.CharField(max_length=150)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.CharField(default='true', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'table_user',
            },
        ),
        migrations.CreateModel(
            name='landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150, unique=True)),
                ('alternate_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, default='landlord_photos/default.jpg', null=True, upload_to='landlord_photos')),
                ('id_proof_type', models.CharField(max_length=150)),
                ('id_proof_number', models.CharField(max_length=150)),
                ('empId', models.CharField(max_length=150)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default='true', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'table_landlord',
            },
        ),
    ]
