# Generated by Django 5.1.5 on 2025-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('salary', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, default='employee_photos/default.jpg', null=True, upload_to='employee_photos/')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('employee', 'employee')], default='employee', max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employee',
            },
        ),
        migrations.DeleteModel(
            name='empolyee',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='landlord',
            options={'verbose_name': 'landlord', 'verbose_name_plural': 'landlords'},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='empId',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='empId',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='token',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='agent',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='agent',
            table='agent',
        ),
        migrations.AlterModelTable(
            name='landlord',
            table='landlord',
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='tenant',
        ),
    ]
