# Generated by Django 5.1.5 on 2025-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0002_employee_delete_empolyee_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
