# Generated by Django 5.1.5 on 2025-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0003_alter_agent_password_alter_employee_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='contact',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
