# Generated by Django 5.1.5 on 2025-04-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0004_alter_agent_contact_alter_employee_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
