# Generated by Django 5.1.5 on 2025-04-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0005_alter_agent_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
