# Generated by Django 5.1.5 on 2025-04-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0006_remove_agent_status_remove_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(default='agent', max_length=100),
        ),
        migrations.AddField(
            model_name='landlord',
            name='role',
            field=models.CharField(default='landlord', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='role',
            field=models.CharField(default='tenant', max_length=100),
        ),
    ]
