# Generated by Django 5.1.5 on 2025-04-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0007_agent_role_landlord_role_tenant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('superAdmin', 'superAdmin')], default='admin', max_length=50),
        ),
    ]
