# Generated by Django 5.1.5 on 2025-04-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0009_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
