# Generated by Django 5.1.5 on 2025-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0010_landlord_emp_id_landlord_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
