# Generated by Django 5.1.5 on 2025-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0011_alter_employee_is_active_alter_landlord_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_id', models.CharField(max_length=150)),
                ('building_name', models.CharField(max_length=150)),
                ('building_type', models.CharField(max_length=150)),
                ('room_type', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('amenities', models.CharField(blank=True, max_length=255, null=True)),
                ('furnishing_status', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, default='building_photos/default.jpg', null=True, upload_to='building_photos/')),
                ('total_floors', models.CharField(max_length=150)),
                ('total_rooms', models.CharField(max_length=150)),
                ('min_rent', models.CharField(blank=True, max_length=150, null=True)),
                ('max_rent', models.CharField(blank=True, max_length=150, null=True)),
                ('locality', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('street_address', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=150)),
                ('availability_status', models.CharField(max_length=150)),
                ('emp_id', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
