# Generated by Django 5.1.5 on 2025-04-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0012_building'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='tbl_building',
        ),
    ]
