# Generated by Django 5.1.5 on 2025-04-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0013_alter_building_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=150)),
                ('agent_id', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=150, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=150, null=True)),
                ('landlord_id', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=15)),
                ('booking_date', models.DateTimeField()),
                ('check_in_date', models.DateTimeField()),
                ('duration_of_stay', models.CharField(blank=True, max_length=150, null=True)),
                ('rent_amt', models.CharField(max_length=150)),
                ('deposit_amt', models.CharField(max_length=150)),
                ('room_type', models.CharField(blank=True, max_length=150, null=True)),
                ('booking_statues', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking_details',
            },
        ),
    ]
