# Generated by Django 5.1.5 on 2025-04-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0014_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_statues',
            new_name='booking_status',
        ),
    ]
