# Generated by Django 5.1.5 on 2025-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0015_rename_booking_statues_booking_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=150)),
                ('payment_amt', models.CharField(max_length=150)),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_status', models.CharField(max_length=150)),
                ('payment_date', models.DateTimeField()),
                ('emp_id', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_details',
            },
        ),
    ]
