# Generated by Django 5.1.5 on 2025-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0016_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(blank=True, max_length=150, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=150, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'review_details',
            },
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='is_active',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='emp_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
