# Generated by Django 5.1.5 on 2025-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0017_review_remove_enquiry_is_active_enquiry_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='landlord_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
