# Generated by Django 5.1.5 on 2025-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0018_alter_building_landlord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
