# Generated by Django 5.1.5 on 2025-04-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0019_alter_enquiry_contact_alter_enquiry_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='occupancy',
        ),
    ]
