# Generated by Django 5.1.5 on 2025-05-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0022_building_lattitude_building_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emp_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
