# Generated by Django 5.1.5 on 2025-05-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roomkhojlo_APP', '0023_agent_emp_id_tenant_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
